# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93da580e9672df85480d3cd925ff446a1acebe611cf1d34f9df223781dc7e082e8e8d8abd4a2fbee6abb27b0db342bd803997fd6eb0be98d5faf842bd3ae1f62

test:
  secret_key_base: 7eadd9424d3841acd5719f7d55a7bac3c4910dcde1af6d9514b9af3df2687ff1b0352478834854c1787f0ec148ddc1bc2b4d15a414d42f6259b85970da4e2658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
